import Link from "next/link";
import { AGREEMENT_SUMMARY, CURRENT_AGREEMENT_VERSION } from "@/lib/hosted-audio/agreement";

export function Licencing() {
  return (
    <article className="space-y-10 text-sm leading-7 text-muted-foreground [&_h2]:mb-3 [&_h2]:text-xl [&_h2]:font-medium [&_h2]:text-foreground [&_a]:underline [&_a]:underline-offset-4 [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6">
      <p className="text-xs">Version 1.0 · Last updated <time dateTime="2026-09-20">20 September 2026</time></p>
      <p>VisAmp is operated by VisArc in South Australia, Australia. Creators and artists keep their rights. The permissions needed for visualisations, visual assets and music are separate: permission for one does not automatically cover the others. This page explains those permissions alongside our <Link href="/site/terms-and-conditions">Terms and Conditions</Link>.</p>

      <section aria-labelledby="licencing-visualisations">
        <h2 id="licencing-visualisations">Public visualisations and forks</h2>
        <p>Publishing a visualisation under our terms gives other users permission to play it and fork it within VisAmp. A fork is a copy that can be changed and published as another visualisation on the platform. This permission is non-exclusive and royalty-free; the original creator keeps their rights, and a fork’s creator has only the rights they hold in their own contributions.</p>
        <p>Keep the original creator’s attribution and the fork lineage where provided. Do not pass off someone else’s work as entirely your own. A public visualisation is not automatically open source, public domain or covered by a Creative Commons licence.</p>
        <p>Redistributing source code, publishing a recording on social media, using a visualisation in an advertisement or using it elsewhere requires separate permission from the relevant rights holders, unless a separate licence or the law already permits the use. Being able to view or technically copy something does not grant that permission.</p>
        <p>Making the original private or deleting it does not automatically remove independently saved forks. Permissions apply only where the relevant rights holder has granted them; these pages do not relicense older uploads without their agreement. For a rights concern, contact <a href="mailto:admin@visamp.io">admin@visamp.io</a>.</p>
      </section>

      <section aria-labelledby="licencing-assets">
        <h2 id="licencing-assets">Images, vectors and 3D models</h2>
        <p>Only upload assets you own or are authorised to use and share in the ways you select. A file found online, purchased from a stock library or generated by a tool is not necessarily licensed for sharing with other VisAmp users. Check any attribution, modification and redistribution conditions first.</p>
        <p>When you make an asset public under these terms, you grant other VisAmp users a non-exclusive, royalty-free permission to incorporate it into visualisations on VisAmp and into videos exported from those visualisations, including sharing those videos outside the platform. This permission does not cover redistributing the standalone asset, reselling it as stock, or claiming ownership of it. Preserve required attribution and third-party notices.</p>
        <p>The asset permission is separate from the visualisation and music permissions. An exported video containing someone else’s visualisation or music still needs any additional permission those works require. You can export your own original visualisation using a shared asset, provided you also have the necessary music and other rights.</p>
        <p>Private assets are not offered in the shared asset library. Publishing an asset makes it available to other creators. Making a previously public asset private removes it from discovery for new use; existing published visualisations referencing it can continue to load it. It is not the same as withdrawing an asset because of an infringement or safety issue.</p>
        <p>If an asset should be withdrawn, email <a href="mailto:admin@visamp.io">admin@visamp.io</a> with its link and the reason. Withdrawal may affect visualisations and forks that depend on it. Removing a hosted copy cannot recall copies already downloaded.</p>
      </section>

      <section aria-labelledby="licencing-hosted-music">
        <h2 id="licencing-hosted-music">Uploading and hosting music</h2>
        <p>The artist upload agreement is accepted separately during music onboarding. The currently offered agreement is version <time dateTime={CURRENT_AGREEMENT_VERSION}>{CURRENT_AGREEMENT_VERSION}</time>:</p>
        <ul>{AGREEMENT_SUMMARY.map((term) => <li key={term}>{term}</li>)}</ul>
        <p>The version you accepted governs your upload. This explanatory page does not replace it or extend its licence. You keep ownership and can release or license your music elsewhere.</p>
        <p>You need authority covering both the recording and the underlying composition or publishing rights. Check any co-writer, label, publisher, performer, sample or artwork permissions that apply. Owning a recording does not necessarily mean you control every right in the song.</p>
        <p>If you upload on an artist’s behalf, obtain their authority before claiming their name or submitting music. You may be asked to provide evidence. An artist profile or accepted upload is not a determination of legal ownership.</p>
      </section>

      <section aria-labelledby="licencing-listening">
        <h2 id="licencing-listening">Listening and preferred tracks</h2>
        <p>You may listen to music through VisAmp’s authorised player features while it is available. Setting a preferred track links a visualisation to a playback choice; it does not transfer music rights to the visualisation creator or to anyone who forks it.</p>
        <p>The hosted-music permission does not automatically cover downloading or redistributing recordings, uploading audiovisual recordings to another platform, advertising, livestreaming, public performance or commercial synchronisation. Those uses may require separate permissions for the music, the recording and the visualisation.</p>
        <p>For use outside VisAmp, contact the appropriate creators and music rights holders. VisArc cannot grant rights it does not hold. Credit alone does not replace permission.</p>
      </section>

      <section aria-labelledby="licencing-external">
        <h2 id="licencing-external">SoundCloud and local audio</h2>
        <p>SoundCloud playback remains subject to SoundCloud’s terms and the rights holders’ permissions. A public track URL is not a general licence to download, synchronise, record or republish the music.</p>
        <p>Local-file playback lets you use files from your device; it does not publish them to the VisAmp catalogue or give you new rights in them. You are responsible for any permissions needed for your intended use, including events, broadcasts and recordings.</p>
      </section>

      <section aria-labelledby="licencing-ai">
        <h2 id="licencing-ai">AI output, software and branding</h2>
        <p>Paying for AI generation provides the generation service, not a guarantee that its output is unique, protected by copyright or free of third-party rights. Check the material you submit and review results before publishing. When you publish a generated visualisation, the same content rules apply.</p>
        <p>These content permissions do not grant rights to VisArc’s or VisAmp’s names, logos or service software. Components distributed under separate open-source licences remain subject to those licences and notices. Do not suggest an endorsement or partnership without permission.</p>
      </section>

      <section aria-labelledby="licencing-disputes">
        <h2 id="licencing-disputes">Permission requests and rights disputes</h2>
        <p>For licensing questions, email <a href="mailto:admin@visamp.io">admin@visamp.io</a>. Identify the visualisation, asset or track; explain the intended use, where it will appear and whether it is commercial. We can help direct the request, but permission must come from someone authorised to grant it.</p>
        <p>For an unauthorised artist claim, follow the <Link href="/dispute">artist claim dispute process</Link>. For other rights complaints, email the relevant links, your relationship to the work, the basis of your claim and the action you are requesting. We may ask for further evidence, restrict disputed material during review, or contact the uploader. A complaint does not automatically transfer ownership or an account.</p>
        <p>Nothing on this page limits rights or exceptions provided by applicable law. If you are unsure whether a proposed use is covered, get advice from a qualified professional before proceeding.</p>
      </section>
    </article>
  );
}
